quarkus.http.root-path=/WeatherService
net.ipmdecisions.weatherservice.SLU_LANTMET_ADAPTER_CREDENTIALS_PARAMSTRING=${SLU_LANTMET_ADAPTER_CREDENTIALS_PARAMSTRING}
net.ipmdecisions.weatherservice.WEATHER_API_URL=${WEATHER_API_URL}
net.ipmdecisions.weatherservice.BEARER_TOKEN_fr_meteo-concept_api=${BEARER_TOKEN_fr_meteo-concept_api}
net.ipmdecisions.weatherservice.LWD_LSTM_HOSTNAME==${LWD_LSTM_HOSTNAME=}